name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Hugo site
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.145.0'

      - name: Build Hugo site
        run: hugo --baseURL https://mattfors.github.io/dance-calendar/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
